apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "55.6.0"
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            scrapeInterval: 10s
            evaluationInterval: 30s
          ingress:
            enabled: true
            ingressClassName: kong
            hosts:
            - prometheus.local
        grafana:
          persistence:
            enabled: true  # enable persistence using Persistent Volumes
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default' # Configure a dashboard provider file to
                orgId: 1        # put Kong dashboard into.
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
          dashboards:
            default:
              kong-dash:
                gnetId: 7424  # Install the following Grafana dashboard in the
                revision: 11  # instance: https://grafana.com/dashboards/7424
                datasource: Prometheus
              kic-dash:
                gnetId: 15662
                datasource: Prometheus
          ingress:
            enabled: true
            ingressClassName: kong
            hosts:
              - "grafana.local"
          grafana.ini:
            server:
              domain: grafana.local
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
      