apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfranconeto-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jfranconetoo/kind-kong-nginx.git
    targetRevision: HEAD
    path: apps/jfranconeto-app
  destination:
    server: https://kubernetes.default.svc
    namespace: jfranconeto-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true