apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: "0.10.1"
    chart: ingress
    helm:
      parameters:
      - name: "ingressController.installCRDs"
        value: "false"
        forceString: true # ensures that value is treated as a string
      valuesObject: 
        gateway:
          serviceMonitor:
            enabled: true
            labels:
             release: promstack
        # plugins:
        #   configMaps:                # change this to 'secrets' if you created a secret
        #   - name: kong-plugin-myheader
        #     pluginName: myheader
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true